### ISSUE TITLE
Gimme a good reason why should I use this?

### ISSUE THREAD

**Issue by idotCoder** [CTK-WARRIOR/Discord-Buttons-Plugin#1]
As said gimme a good reason why should I use this over [discord-buttons](https://github.com/AngeloCore/discord-buttons) its totally copied from discord-buttons.

**Comment by idotCoder** [comment]
discord-buttons is wayy better than this.

**Comment by CTK-WARRIOR** [comment]
Gimme one reason how is this a issue, please do not create false issue.

**Comment by idotCoder** [comment]
> Gimme one reason how is this a issue, please do not create false issue.

its not a issue, its a question

**Comment by CTK-WARRIOR** [comment]
Learn first for what reason **Github Issue** are used, if you want to talk about who copied who then we can talk in server : https://withwin.in/dbd

**Comment by idotCoder** [comment]
> first Learn for what reason **Github Issue** are used, if you want to talk about who copied who then we can talk in server : https://withwin.in/dbd

Why should I click on a link that will IPLOG me?

**Comment by idotCoder** [comment]
Also this is the right place to discuss about your repo.

**Comment by idotCoder** [comment]
It's a issue with your package

**Comment by idotCoder** [comment]
You have copied the code and the entire idea from discord-buttons

**Comment by TheLastGamer18** [comment]
I don't see the code "copied" and you can say that discord-buttons code is "copied" too

**Comment by CTK-WARRIOR** [comment]
DO NOT USE IF YOU DONT LIKE IT - some legend said for some brainless dude

**Comment by idotCoder** [comment]
> I don't see the code "copied" and you can say that discord-buttons code is "copied" too

really how

**Comment by idotCoder** [comment]
> DO NOT USE IT IF YOU DONT LIKE IT - some legend said for some brainless dude

i am not using it just showing the world how bad you are

**Comment by AngeloCore** [comment]
wtf

**Comment by CTK-WARRIOR** [comment]
owo, owner of the alt just joined the useless chat

**Comment by TheLastGamer18** [comment]
> > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> 
> really how
https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12

**Comment by idotCoder** [comment]
> > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > 
> > 
> > really how
> > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12

and? Check the upload date

**Comment by CTK-WARRIOR** [comment]
You guys acting like you are some kind of Founder of Buttons

**Comment by idotCoder** [comment]
![image](https://user-images.githubusercontent.com/85446993/120930120-a1e98180-c709-11eb-89e5-b57a94f234ba.png)
![image](https://user-images.githubusercontent.com/85446993/120930133-b3328e00-c709-11eb-80f2-a379b2a54d6c.png)

**Comment by TheLastGamer18** [comment]
> > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > 
> > > 
> > > really how
> > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> 
> and? Check the upload date

ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name

**Comment by idotCoder** [comment]
> > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > 
> > > > 
> > > > really how
> > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > 
> > 
> > and? Check the upload date
> 
> ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name

why should I "think" of something when I am speaking the truth

**Comment by AngeloCore** [comment]
> > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > 
> > > 
> > > really how
> > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> 
> and? Check the upload date

We were first?!?!?

**Comment by AngeloCore** [comment]
Also
![N59GzIiOsU](https://user-images.githubusercontent.com/62988428/120930255-2b428900-c6f5-11eb-8436-9784f0eca306.gif)

**Comment by idotCoder** [comment]
LMAO what a skid

**Comment by CTK-WARRIOR** [comment]
Thats i do when you dont want to promote some else package

**Comment by SilentJungle399** [comment]
I don't think this was the intention of github issues, you're just making a mountain out of a mole-hill, it's obvious that you want to promote your own package on ctk's channel, and now you can't stand that the latter created his own package to make it simple for his viewers.

**Comment by TheLastGamer18** [comment]
> > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > 
> > > > > 
> > > > > really how
> > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > 
> > > 
> > > and? Check the upload date
> > 
> > 
> > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> 
> why should I "think" of something when I am speaking the truth

my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues

**Comment by idotCoder** [comment]
> I don't think this was the intention of github issues, you're just making a mountain out of a mole-hill, it's obvious that you want to promote your own package on ctk's channel, and now you can't stand that the latter created his own package to make it simple for his viewers.

by copying the code?

**Comment by idotCoder** [comment]
> > > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > > 
> > > > > > 
> > > > > > really how
> > > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > > 
> > > > 
> > > > and? Check the upload date
> > > 
> > > 
> > > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> > 
> > 
> > why should I "think" of something when I am speaking the truth
> 
> my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues

ITS A ISSUE
RELATED
TO THE 
PACKAGE

**Comment by idotCoder** [comment]
god

**Comment by AngeloCore** [comment]
> Thats i do when i dont want to promote some else package

I was willing to pay a large sum, but because you saw that my package was growing very fast, and you said "why don't I do it too"

**Comment by SilentJungle399** [comment]
> > I don't think this was the intention of github issues, you're just making a mountain out of a mole-hill, it's obvious that you want to promote your own package on ctk's channel, and now you can't stand that the latter created his own package to make it simple for his viewers.
> 
> by copying the code?

Keeping that aside for a moment, how does this concern you, I understand angelo created this package, he has the right to butt in here, but what's your incentive here?

**Comment by TheLastGamer18** [comment]
> > > > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > > > 
> > > > > > > 
> > > > > > > really how
> > > > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > > > 
> > > > > 
> > > > > and? Check the upload date
> > > > 
> > > > 
> > > > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> > > 
> > > 
> > > why should I "think" of something when I am speaking the truth
> > 
> > 
> > my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues
> 
> ITS A ISSUE
> RELATED
> TO THE
> PACKAGE

you again ignored what I stated first, that if its a common name it shouldnt be called copied, a lot of people can have same ideas for something

**Comment by idotCoder** [comment]
> > > I don't think this was the intention of github issues, you're just making a mountain out of a mole-hill, it's obvious that you want to promote your own package on ctk's channel, and now you can't stand that the latter created his own package to make it simple for his viewers.
> > 
> > 
> > by copying the code?
> 
> Keeping that aside for a moment, how does this concern you, I understand angelo created this package, he has the right to butt in here, but what's your incentive here?

why does that matter to you in ANYWAY

**Comment by SilentJungle399** [comment]
![image](https://user-images.githubusercontent.com/75272148/120930427-ceea6400-c70a-11eb-9d91-73a40cc9dad3.png)

Ah I see, no one bothered to join your cause, so you're just creating alts to waste your's and other people's time.
Kids

**Comment by AngeloCore** [comment]
> > > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > > 
> > > > > > 
> > > > > > really how
> > > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > > 
> > > > 
> > > > and? Check the upload date
> > > 
> > > 
> > > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> > 
> > 
> > why should I "think" of something when I am speaking the truth
> 
> my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues

Once the buttons went public and our package started growing fast, everyone started copying the idea with the goal of having a big and famous package too

**Comment by TheLastGamer18** [comment]
> > > > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > > > 
> > > > > > > 
> > > > > > > really how
> > > > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > > > 
> > > > > 
> > > > > and? Check the upload date
> > > > 
> > > > 
> > > > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> > > 
> > > 
> > > why should I "think" of something when I am speaking the truth
> > 
> > 
> > my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues
> 
> Once the buttons went public and our package started growing fast, everyone started copying the idea with the goal of having a big and famous package too

so are you saying that discord.js copy your code too

**Comment by idotCoder** [comment]
> ![image](https://user-images.githubusercontent.com/75272148/120930427-ceea6400-c70a-11eb-9d91-73a40cc9dad3.png)
> 
> Ah I see, no one bothered to join your cause, so you're just creating alts to waste your's and other people's time.
> Kids

Kids? And what are you an old uncle?

**Comment by SilentJungle399** [comment]
> > ![image](https://user-images.githubusercontent.com/75272148/120930427-ceea6400-c70a-11eb-9d91-73a40cc9dad3.png)
> > Ah I see, no one bothered to join your cause, so you're just creating alts to waste your's and other people's time.
> > Kids
> 
> Kids? And what are you an old uncle?

Nope, I'm just more mature.

**Comment by idotCoder** [comment]
> ![image](https://user-images.githubusercontent.com/75272148/120930427-ceea6400-c70a-11eb-9d91-73a40cc9dad3.png)
> 
> Ah I see, no one bothered to join your cause, so you're just creating alts to waste your's and other people's time.
> Kids

STOP stalking me like god

**Comment by AngeloCore** [comment]
> > > > > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > > > > 
> > > > > > > > 
> > > > > > > > really how
> > > > > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > > > > 
> > > > > > 
> > > > > > and? Check the upload date
> > > > > 
> > > > > 
> > > > > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> > > > 
> > > > 
> > > > why should I "think" of something when I am speaking the truth
> > > 
> > > 
> > > my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues
> > 
> > 
> > Once the buttons went public and our package started growing fast, everyone started copying the idea with the goal of having a big and famous package too
> 
> so are you saying that discord.js copied your code too

Actually we first created the `MessageButton` class and all...

**Comment by idotCoder** [comment]
> > > ![image](https://user-images.githubusercontent.com/75272148/120930427-ceea6400-c70a-11eb-9d91-73a40cc9dad3.png)
> > > Ah I see, no one bothered to join your cause, so you're just creating alts to waste your's and other people's time.
> > > Kids
> > 
> > 
> > Kids? And what are you an old uncle?
> 
> Nope, I'm just more mature.

Prove it

**Comment by AngeloCore** [comment]
> ![image](https://user-images.githubusercontent.com/75272148/120930427-ceea6400-c70a-11eb-9d91-73a40cc9dad3.png)
> 
> Ah I see, no one bothered to join your cause, so you're just creating alts to waste your's and other people's time.
> Kids

Are you saying that @idotCoder is me?

**Comment by SilentJungle399** [comment]
> > > > > > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > really how
> > > > > > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > > > > > 
> > > > > > > 
> > > > > > > and? Check the upload date
> > > > > > 
> > > > > > 
> > > > > > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> > > > > 
> > > > > 
> > > > > why should I "think" of something when I am speaking the truth
> > > > 
> > > > 
> > > > my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues
> > > 
> > > 
> > > Once the buttons went public and our package started growing fast, everyone started copying the idea with the goal of having a big and famous package too
> > 
> > 
> > so are you saying that discord.js copied your code too
> 
> Actually we first created the `MessageButton` class and all...

All this fuss because the `MessageButton` class name was the same alltogather?

**Comment by CTK-WARRIOR** [comment]
![image](https://user-images.githubusercontent.com/57840201/120930531-43250780-c70b-11eb-8529-2ec6b86f82c7.png)

**Comment by TheLastGamer18** [comment]
> > > > > > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > really how
> > > > > > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > > > > > 
> > > > > > > 
> > > > > > > and? Check the upload date
> > > > > > 
> > > > > > 
> > > > > > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> > > > > 
> > > > > 
> > > > > why should I "think" of something when I am speaking the truth
> > > > 
> > > > 
> > > > my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues
> > > 
> > > 
> > > Once the buttons went public and our package started growing fast, everyone started copying the idea with the goal of having a big and famous package too
> > 
> > 
> > so are you saying that discord.js copied your code too
> 
> Actually we first created the `MessageButton` class and all...

so why aren't you going to the discord.js repo and saying this there?

**Comment by SilentJungle399** [comment]
> > > > ![image](https://user-images.githubusercontent.com/75272148/120930427-ceea6400-c70a-11eb-9d91-73a40cc9dad3.png)
> > > > Ah I see, no one bothered to join your cause, so you're just creating alts to waste your's and other people's time.
> > > > Kids
> > > 
> > > 
> > > Kids? And what are you an old uncle?
> > 
> > 
> > Nope, I'm just more mature.
> 
> Prove it

Not bothered to

**Comment by idotCoder** [comment]
> > > > > > > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > really how
> > > > > > > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > > > > > > 
> > > > > > > > 
> > > > > > > > and? Check the upload date
> > > > > > > 
> > > > > > > 
> > > > > > > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> > > > > > 
> > > > > > 
> > > > > > why should I "think" of something when I am speaking the truth
> > > > > 
> > > > > 
> > > > > my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues
> > > > 
> > > > 
> > > > Once the buttons went public and our package started growing fast, everyone started copying the idea with the goal of having a big and famous package too
> > > 
> > > 
> > > so are you saying that discord.js copied your code too
> > 
> > 
> > Actually we first created the `MessageButton` class and all...
> 
> so why aren't you going to the discord.js repo and saying this there?

because this repo is also copied

**Comment by SilentJungle399** [comment]
> > > > > > > > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > really how
> > > > > > > > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > and? Check the upload date
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> > > > > > > 
> > > > > > > 
> > > > > > > why should I "think" of something when I am speaking the truth
> > > > > > 
> > > > > > 
> > > > > > my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues
> > > > > 
> > > > > 
> > > > > Once the buttons went public and our package started growing fast, everyone started copying the idea with the goal of having a big and famous package too
> > > > 
> > > > 
> > > > so are you saying that discord.js copied your code too
> > > 
> > > 
> > > Actually we first created the `MessageButton` class and all...
> > 
> > 
> > so why aren't you going to the discord.js repo and saying this there?
> 
> because this repo is also copied

prove it

**Comment by CTK-WARRIOR** [comment]
why not we just let his alt play with himself

**Comment by TheLastGamer18** [comment]
> > > > > > > > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > really how
> > > > > > > > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > and? Check the upload date
> > > > > > > > 
> > > > > > > > 
> > > > > > > > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> > > > > > > 
> > > > > > > 
> > > > > > > why should I "think" of something when I am speaking the truth
> > > > > > 
> > > > > > 
> > > > > > my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues
> > > > > 
> > > > > 
> > > > > Once the buttons went public and our package started growing fast, everyone started copying the idea with the goal of having a big and famous package too
> > > > 
> > > > 
> > > > so are you saying that discord.js copied your code too
> > > 
> > > 
> > > Actually we first created the `MessageButton` class and all...
> > 
> > 
> > so why aren't you going to the discord.js repo and saying this there?
> 
> because this repo is also copied

AGAIN, the main point is dodged, why arent you going to discord.js repo and creating the same issue

**Comment by AngeloCore** [comment]
It doesn't matter if I hadn't posted my package and you wouldn't be posting yours and waiting for discord.js
As happened with the slash commands

**Comment by SilentJungle399** [comment]
> why not we just let his alt play with himself

yeah nice role playing

**Comment by AngeloCore** [comment]
> why not we just let his alt play with himself

MY ALT?!??!

**Comment by CTK-WARRIOR** [comment]
This issue is total JOKE lmao like the issue owner

**Comment by TheLastGamer18** [comment]
> It doesn't matter if I hadn't posted my package and you wouldn't be posting yours and waiting for discord.js
> As happened with the slash commands

how do you stand so confident by that? People's opinions can change from time to time, if he didn't want to make it earlier he can make it later

**Comment by idotCoder** [comment]
> > > > > > > > > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > really how
> > > > > > > > > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > and? Check the upload date
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> > > > > > > > 
> > > > > > > > 
> > > > > > > > why should I "think" of something when I am speaking the truth
> > > > > > > 
> > > > > > > 
> > > > > > > my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues
> > > > > > 
> > > > > > 
> > > > > > Once the buttons went public and our package started growing fast, everyone started copying the idea with the goal of having a big and famous package too
> > > > > 
> > > > > 
> > > > > so are you saying that discord.js copied your code too
> > > > 
> > > > 
> > > > Actually we first created the `MessageButton` class and all...
> > > 
> > > 
> > > so why aren't you going to the discord.js repo and saying this there?
> > 
> > 
> > because this repo is also copied
> 
> prove it

look at it yourself skid

**Comment by SilentJungle399** [comment]
watch the alt account go total passive after this issue gets cooled down, now new projects, no repos, the incentive for the acc creation was just this issue

**Comment by idotCoder** [comment]
> watch the alt account go total passive after this issue gets cooled down, no new projects, no repos, the incentive for the acc creation was just this issue

Why
Do
You
Care

**Comment by SilentJungle399** [comment]
> > > > > > > > > > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > really how
> > > > > > > > > > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > and? Check the upload date
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > why should I "think" of something when I am speaking the truth
> > > > > > > > 
> > > > > > > > 
> > > > > > > > my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues
> > > > > > > 
> > > > > > > 
> > > > > > > Once the buttons went public and our package started growing fast, everyone started copying the idea with the goal of having a big and famous package too
> > > > > > 
> > > > > > 
> > > > > > so are you saying that discord.js copied your code too
> > > > > 
> > > > > 
> > > > > Actually we first created the `MessageButton` class and all...
> > > > 
> > > > 
> > > > so why aren't you going to the discord.js repo and saying this there?
> > > 
> > > 
> > > because this repo is also copied
> > 
> > 
> > prove it
> 
> look at it yourself skid

Nope, you're such a brilliant bright guy who himself created a github account just to address this issue, please care to prove it, if you cant, just stop

**Comment by TheLastGamer18** [comment]
And why do you care about this small package, your package is already famous enough and people are mature enough to not use "copied" packages

**Comment by CTK-WARRIOR** [comment]
ok boys, thats enough

**Comment by idotCoder** [comment]
> > > > > > > > > > > > > > > I don't see the code "copied" and you can say that discord-buttons code is "copied" too
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > really how
> > > > > > > > > > > > > > https://github.com/discordjs/discord.js/blob/master/src/structures/MessageButton.js#L12
> > > > > > > > > > > > 
> > > > > > > > > > > > 
> > > > > > > > > > > > and? Check the upload date
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > ok, think of it this way, if the "original" owner did it first, and discord.js devs later, it just shows that the constructor name and method names are common so you can't say it is copied if its a common name
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > why should I "think" of something when I am speaking the truth
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > my point still stands, if its a common name then stop saying that its copied + sending a message written a month ago doesnt relate to his opinions now and stop misusing github issues
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Once the buttons went public and our package started growing fast, everyone started copying the idea with the goal of having a big and famous package too
> > > > > > > 
> > > > > > > 
> > > > > > > so are you saying that discord.js copied your code too
> > > > > > 
> > > > > > 
> > > > > > Actually we first created the `MessageButton` class and all...
> > > > > 
> > > > > 
> > > > > so why aren't you going to the discord.js repo and saying this there?
> > > > 
> > > > 
> > > > because this repo is also copied
> > > 
> > > 
> > > prove it
> > 
> > 
> > look at it yourself skid
> 
> Nope, you're such a brilliant bright guy who himself created a github account just to address this issue, please care to prove it, if you cant, just stop

> Keeping that aside for a moment, how does this concern you, I understand angelo created this package, he has the right to butt in here, but what's your incentive here?
