### ISSUE TITLE
Use the master branch of DJS

### ISSUE THREAD

**Issue by imyanice** [CTK-WARRIOR/Discord-Buttons-Plugin#2]
Please update your package he is deprecated ⛔️ !

**Comment by Yan-Jobs** [comment]
READ THE NEW DJSV13 DOCS

**Comment by imyanice** [comment]
Heyyy your package is deprecated and only works with older versions of djs. The new docs are available here: https://deploy-preview-674--discordjs-guide.netlify.app/interactions/buttons.html !

**Comment by CTK-WARRIOR** [comment]
This package is built to work with v12
